separator_conf:
  input_dim: 8192
  n_srcs: 4
  n_fft: 8192
  stride: 4096
  window: "hann"
  n_imics: 5
  n_layers: 3
  lstm_hidden_units: 128
  attn_n_head: 1
  attn_approx_qk_dim: 512
  emb_dim: 16
  emb_ks: 8
  emb_hs: 1
  activation: "prelu"
  eps: 1.0e-5

optimizer_conf:
  lr: 1.0e-3
  eps: 1.0e-07
  weight_decay: 0

dataset:
  root_dir: /mnt/share/jmontoro/2024_CMMSE_RaySpaceDNN/loc/
  batch_size: 3
  seed: 115
  train_valid_split_sizes:
    - .8
    - .2
  num_workers: 1

train:
  num_epochs: 50
  exp_name: BeamspaceDNN